language: node_js
node_js:
  - "10"
services:
  - postgresql
before_script:
  - psql -c 'DROP DATABASE IF EXISTS wayfarer;' -U postgres
  - psql -c 'create database wayfarer;' -U postgres
env:
  - SECRETKEY='secretjwtkey'  
script:
  - npm test
after_success:
  - nyc report --reporter=text-lcov | coveralls
  on:
    branch: ft-book-seat-endpoint-166997580
