language: node_js
node_js:
  - "10"
services:
  - postgresql
  - docker
before_script:
  - psql -c 'DROP DATABASE IF EXISTS wayfarer;' -U postgres
  - psql -c 'create database wayfarer;' -U postgres
env:
  - SECRETKEY='secretjwtkey'  
script:
  - npm test
before_deploy:
  - rm -rf .tmp
  - rm -rf .DS_Store
  - rm -rf node_modules
  - export ELASTIC_BEANSTALK_ENV=node-server-${TRAVIS_BRANCH}
  - zip -r --exclude=\*.git\* --exclude=\*.DS_Store\* --exclude=\*test\  node-server.zip
  - export ELASTIC_BEANSTALK_LABEL=git-$(git rev-parse --verify HEAD --short)
  - export ELASTIC_BEANSTALK_DESCRIPTION=https://github.com/sumn2u/node-server/tree/$(git
    rev-parse HEAD)
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAVIIZVYIQWED3RABC
  secret_access_key: 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
  region: "us-east-2"  
  app: "wayfarer"
  env: "Wayfarer-env"
  only_create_app_version: false
after_deploy:
- rm node-server.zip
after_success:
  - nyc report --reporter=text-lcov | coveralls
  on:
    branch: ft-book-seat-endpoint-166997580

